name       : gnome-shell-extension-topicons-plus
version    : '12'
release    : 10
source     :
    - https://github.com/MartinPL/Tray-Icons-Reloaded/archive/refs/tags/12.tar.gz : 319b5318c8d21e619506146bb029eba933f203d17374385d1b2b4013c9bf6648
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Extension that enables legacy tray items to appear in the top tray.
description: |
    Gnome Shell Extension that enables legacy tray items to appear in the top tray.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    export gseDir=$installdir/usr/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl/
    install -dm00755 ${gseDir}
    install -Dm00644 schemas/org.*xml $installdir/usr/share/glib-2.0/schemas/
    rm -r schemas
    cp -R $workdir/* ${gseDir}
    chmod 00644 ${gseDir}/*
    rm ${gseDir}/{LICENSE,README.md}
