name       : gnome-shell-extension-topicons-plus
version    : '22'
release    : 7
source     :
    - git|https://github.com/phocean/TopIcons-plus.git : ad2dd1ad48ad9a5899e14a9e0873244a3e15b82e
license    : GPL-2.0-only
component  : desktop.gnome
summary    : Gnome Shell Extension that enables legacy tray items to appear in the top tray.
description: |
    Gnome Shell Extension that enables legacy tray items to appear in the top tray.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
setup      : |
    rm -r Makefile screenshots
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    export gseDir=$installdir/usr/share/gnome-shell/extensions/TopIcons@phocean.net/
    install -dm00755 ${gseDir}
    install -Dm00644 schemas/org.*xml $installdir/usr/share/glib-2.0/schemas/
    rm -r schemas
    cp -R $workdir/* ${gseDir}
    chmod 00644 ${gseDir}/*
