name       : gnome-shell-extension-topicons-plus
version    : 20
release    : 1
source     :
    - https://github.com/phocean/TopIcons-plus/archive/v20.tar.gz : 02ffe087b390b277ce3245b3db675977dad0ed5b6503d719e6e868d8a3082825
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Shell Extension that enables legacy tray items to appear in the top tray.
description: |
    Gnome Shell Extension that enables legacy tray items to appear in the top tray.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
setup      : |
    rm -r Makefile screenshots
install    : |
    export gseDir=$installdir/usr/share/gnome-shell/extensions/TopIcons@phocean.net/
    install -dm00644 ${gseDir}
    cp -R $workdir/* ${gseDir}
    chmod 00644 ${gseDir}
